project_id         = "gke-dev-XXXXXX"
cluster_name       = "gke"
env_name           = "dev"
region             = "europe-west3"
network            = "gke-netwrok"
subnetwork         = "gke-subnet"
ip_range_pods_name = "ip-range-pods"
ip_range_services_name = "ip-range-services"
